# Generated by Django 4.2.20 on 2025-04-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='response',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
